services:
  backend:
    build:
      context: ./backend
    command: npm run start
    develop:
      watch:
        - action: rebuild
          path: ./backend/
          target: /home/big-brains/app
          ignore:
            - ./backend/node_modules/
    container_name: app-backend
    ports: 
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
    command: npm run start-frontend
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /home/big-brains/app
          ignore:
            - ./frontend/node_modules/
    container_name: app-frontend
    ports:
      - "8000:8000"
    # links:
    # - backend
